### ISSUE TITLE
Allow ace link in any buffer

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/ace-link#9]
It would be nice if we can use it in any buffer to jump to links currently supported by `ace-link`.

**Comment by abo-abo** [comment]
You can pretty much just call whatever function works already.
For instance, `ace-link-help` works in `ert-results-mode`.

I don't know what else can be done besides that.

**Comment by mrkkrp** [comment]
Hello, I don't know if I should open a separate issue for this, but `ace-link` is really convenient thing, so I would like to have global key binding for it, say <kbd>M-o</kbd>. I've found out that `ace-link-org` works in org mode as well as in markdown mode (and possible in other similar modes as well). This is great, but I first need to open some org file before I can use it for markdown, otherwise I get the following error message in the minibuffer:

> ace-link-org: Symbol's value as variable is void: org-any-link-re

Can you somehow eliminate it, or provide some other command that would work anywhere it can recognize URLs? Thanks for your Emacs-related work, by the way.

**Comment by abo-abo** [comment]
@mrkkrp, thanks. `ace-link-org` will auto-require org now.
